### ISSUE TITLE
[AIP-X][Account abstraction to realize Social recovery]

### ISSUE THREAD

**Issue by 0xkf** [aptos-foundation/AIPs#110]
# AIP Discussion

Discussion and feedback thread for AIP.
I believe that account abstraction function & Social recovery function is needed for Aptos Ecosystem

Link to AIP: 
to realize social key, not only some authority called guardian, but also paymaster function (maybe bundler) is needed.
Let's implement this function watching 

Please refer these pages
https://eips.ethereum.org/EIPS/eip-4337
https://github.com/cardano-foundation/CIPs/pull/309

< Copy AIP text here as well for reader's ease > 
AIP28: Implementation of Account Abstraction in Aptos

overview:
In this proposal, we propose how to apply the concept of Account Abstraction in the Ethereum ecosystem to the Aptos blockchain. Aptos uses the Move language and focuses on UserOperation simulation and validation. In particular, there are restrictions on the information and storage that can be accessed when validating UserOperations.

specification:

For UserOperation validation simulation, call simulateValidation(userop)
Does not call forbidden opcodes and restricts storage access
Storage is limited to data associated with the sender address
The proposed implementation simulates and validates UserOperations and restricts interaction with special contracts such as factories, paymasters and signature aggregators. It also incorporates concepts such as access lists and forbidden opcodes.

Additionally, the concept of alternate mempools has been introduced to allow for specific use cases by whitelisting specific paymasters and signature aggregators.

This AIP28 proposes an implementation of Account Abstraction on the Aptos blockchain, enabling flexible account management with a focus on UserOperation simulation and verification.

Thank you for reading, Please wait for the update...

**Comment by e99243506bigplay** [comment]
Could you explain one by one in detail? I am not familiar to Ethereum and ADA chain. What is "Social key" "Social recovery" in your term?

**Comment by davidiw** [comment]
Aptos has account abstraction, but we haven't documented it. We plan on putting out some guides soon on aptos.dev.

In terms of social recovery, I'd love to see a clear protocol, implementation, and some adoption before pulling it into the framework, as the framework should be sufficiently agile to support it.

However, if during your implementation you find something missing, then that's a strong case for early adoption.

**Comment by 0xkf** [comment]
>Aptos has account abstraction, but we haven't documented it. We plan on putting out some guides soon on aptos.dev.

Waoh! So nice!!
We(my team ) would like to contribute, if possible.

>In terms of social recovery, I'd love to see a clear protocol, implementation, and some adoption before pulling it into the framework, as the framework should be sufficiently agile to support it.
However, if during your implementation you find something missing, then that's a strong case for early adoption.

Please wait till we finish the code review enough.
