### ISSUE TITLE
[AIP-28][Partial voting for on chain governance]

### ISSUE THREAD

**Issue by thepomeranian** [aptos-foundation/AIPs#117]
# AIP 28 - Partial voting for on chain governance

## Summary

With `delegation_pool.move`, end users are able to participate in staking, but the delegation pool owner votes on behalf of the entire pool. Partial voting proposes changes to Aptos Governance by enabling delegators to participate in on chain governance and vote on governance proposals in proportion to their stake amount.

Link to AIP: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-28.md

**Comment by e99243506bigplay** [comment]
Personally, I would like staking in tAPT or stAPT form for more profits, by that, I don't have voting permissions :eyes:

**Comment by davidiw** [comment]
The document doesn't state who is the default voter for a delgator.
