### ISSUE TITLE
[AIP-29][Peer monitoring service]

### ISSUE THREAD

**Issue by thepomeranian** [aptos-foundation/AIPs#118]
# AIP-29 - Peer monitoring service

## Summary

This AIP proposes a new “Peer Monitoring” service that operates on Aptos nodes and allows nodes to track, share and monitor peer information and behaviors. The service aims to: (i) improve node latency and performance, by allowing components to make smarter decisions when disseminating and receiving data; (ii) improve operational quality and reliability, by allowing nodes to dynamically work around failures and unstable peers; (iii) improve peer discovery and selection, by providing a foundation for peer bootstrapping and gossip; (iv) improve security, by allowing nodes to better detect and react to malicious peers and bad behaviors; and (v) improve network observability, by gathering and exporting important network information.

Link to AIP: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-29.md

**Comment by e99243506bigplay** [comment]
Please consider https://en.wikipedia.org/wiki/Great_Firewall this in, when implement this stuff in near future.

**Comment by JoshLind** [comment]
> Please consider https://en.wikipedia.org/wiki/Great_Firewall this in and variant like other country, when implement this stuff in near future.

@e99243506bigplay, can you elaborate? The peer monitoring service will operate over the existing TCP connections established between each node. Regardless of where/how the node is operating, if it is able to connect to the Aptos network, it will share metadata with other nodes via the existing links (and should be unaffected by node locations and/or firewall rules).

**Comment by davidiw** [comment]
This is great! I think this fits into an informational AIP? Is this something we expect to vote on? Can nodes decide independently to turn this on or off without uniformity in the network? If so, I'd propose we continue to iterate on this doc and get more feedback.

**Comment by kinrokinro** [comment]
The main concern is the possibility of divulging any private information on the basis of which you could try to harm the validator/node, but as I can see you think about this too in the AIP itself. Hope it will helps with the connectivity issues between large-distance regions like APAC and LAN/LAS i.e. (but it was more or less fixed with the quorum store IIRC)
