### ISSUE TITLE
[AIP-31][Allowlisting for delegation pool]

### ISSUE THREAD

**Issue by thepomeranian** [aptos-foundation/AIPs#121]
# AIP-31 - Allowlisting for delegation pool

## Summary

This AIP introduces the concept of allowlisting in delegation pools, allowing pool owners to control who can stake in their delegation pool. The feature includes mechanisms for adding or removing delegators from the allowlist and evicting delegators not on the allowlist. By default, a delegation pool is permissionless and does not have an allowlist, until the pool owner explicitly sets an allowlist using this feature.

Link to AIP: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-31.md

**Comment by meetrick** [comment]
I support AIP31, and I think there should be a rule against the delegation pool owner setting the allowlist.
Probably not, but sometimes it could be bad for the ecosystem if delegation pool owners collude with bad intentions.
If I'm wrong(like as misunderstood), please give me feedback. 
Of course, I think most good block-chainers would not harm the ecosystem.

**Comment by sherry-x** [comment]
@meetrick Would you be able to think of some case pool owner might apply the allowlist with bad intention? I think generally setting allowlist doesn't really help the pool owner, since the more people delegate to your pool, you earn more commission, so financially node operators are incentivized to keep things open. As for why allowlisting is helpful, it's described in the motivation, where some entity who wants to run delegation pool, but need to comply with stricter regulation, so this feature give pool owner some control on how they want to manage the pool.

**Comment by meetrick** [comment]
> @meetrick Would you be able to think of some case pool owner might apply the allowlist with bad intention? I think generally setting allowlist doesn't really help the pool owner, since the more people delegate to your pool, you earn more commission, so financially node operators are incentivized to keep things open. As for why allowlisting is helpful, it's described in the motivation, where some entity who wants to run delegation pool, but need to comply with stricter regulation, so this feature give pool owner some control on how they want to manage the pool. 

@sherry-x I agree with the basic intent, of course the delegation pool owner benefits from having more delegates, so I don't think it would be abused.
I was just thinking about the worst-case scenario where the allow list could be abused, like if the owner of all the delegation pools closed the allow list.

**Comment by davidiw** [comment]
Concept and idea make sense. What is the proposed implementation of allowlists?
Furthermore, is this the right design? We're going to add a lot of storage slots just for tracking an allowlist on-chain. I might suggest an alternative approach of multi-agent or a two-stage delegation via an escrow.

**Comment by eliotstock** [comment]
Fully support this. We're an institutional staking provider and we're seeing demand from clients for allow-listed staking pools. Enabling this would unlock increased institutional staking demand, imo.

**Comment by kikakkz** [comment]
> 

Totally agree with that for policy of specific area. It may be a legal issue that pool owner cannot accept all staking from public user.
