### ISSUE TITLE
[AIP-X] [Add Smart Contract developer fee sharing]

### ISSUE THREAD

**Issue by dylanschultzie** [aptos-foundation/AIPs#123]
# AIP Discussion

Implement a fee-sharing mechanism, where half of the transaction fee of a smart contract call will go to the contract’s contributor address(es), and the other half will be burnt as usual, or distributed per [AIP-7](https://github.com/aptos-foundation/AIPs/issues/23). 

Discussion and feedback thread for AIP.

Link to AIP: 

## Motivation

Developers historically have had a difficult time finding funding sources unless they either a) create their own token, or b) are funded by a foundation/grant. In the United States especially, creating your own token creates significant legal hurdles so as to not be considered a security by the SEC. Receiving grants from a foundation is also a difficult task, but not insurmountable. **Adding a clear money/incentivization path for smart contract developers would be a massive boon for the Aptos ecosystem.**

In several competing ecosystems, including [Near](https://near.org/), Smart Contract developers get [30%](https://docs.near.org/concepts/basics/transactions/gas) of all fees spent invoking a smart contract. This incentivizes Smart Contract developers to build on the platform, as getting further mindshare means further smart contract invocations. Further, this gives a clearer incentive/monetary path for developers.

[Juno](https://www.junonetwork.io/) is another such Smart Contract platform that has recently added a [fee-share mechanism](https://commonwealth.im/juno/discussion/7095-implement-a-feesharing-mechanism), with developers receiving 50% of fees and validators receiving the other 50%.

## Pitch

**Describe the solution you'd like**

Rather than burn all fees spent on block creation, share part of it with smart contract developers. Ideally this would be a value configurable by governance so an on-the-fly change can be made.

**Comment by davidiw** [comment]
Would love to see discussion here, I'll share my own personal opinion (this is not the opinion of Aptos Foundation or Labs):

The current proposal needs a lot of work. Reasons why:
* If I don't have any 3rd party contracts, what happens to funds not distributed to other purposes or burned?
* For this to be fair, we'd need weighting based upon how much work done? Or complexity? What dictates that? Does this incentivize less efficient coding paradigms to gain as much in return? The added complexity to the VM may have a non-negligible impact on performance.
* Copying a Move smart contract is trivial, what stops someone from evading this fee and just using their own?
* How much would a contractor stand to gain in this model?
* Are there smart contract developers that would prefer this? Part of my thinking was that you do open source development, so that when someone has a meaningful project, they hire you to help get them over the hump.

Again, personally, I think the cost and effort to do this brings in very small gains especially where the network lies.

**Comment by e99243506bigplay** [comment]
Related Issue: https://github.com/aptos-labs/aptos-core/issues/7146
And, you earned one cent, then someone or groups lose that one cent. think about where the $$$ origin from.

**Comment by lightmark** [comment]
@e99243506bigplay your point on the issue is quite convincing to me.

**Comment by dylanschultzie** [comment]
Hey @davidiw, thanks for your feedback!

>  If I don't have any 3rd party contracts, what happens to funds not distributed to other purposes or burned?

I'm not sure I understand what you're saying here. If you don't have a deployed smart contract, why would you receive a portion of the fee sharing?

> For this to be fair, we'd need weighting based upon how much work done? Or complexity? What dictates that? 

Complexity and work is already calculated when gas is calculated, isn't it?

> Does this incentivize less efficient coding paradigms to gain as much in return? The added complexity to the VM may have a non-negligible impact on performance.

I agree with this, that'd definitely be a concern.

> Copying a Move smart contract is trivial, what stops someone from evading this fee and just using their own?

That's a significant amount of overhead to bypass fees; indeed, deploying and copying a contract would likely cost more than just executing one.

> How much would a contractor stand to gain in this model? Are there smart contract developers that would prefer this? Part of my thinking was that you do open source development, so that when someone has a meaningful project, they hire you to help get them over the hump.

I don't see why a smart contract developer/team wouldn't want to receive additional fees. I'm not sure how fee sharing would conflict with smart contract developers being hired as contractors for development? I may not be understanding the argument you're making here. 

The goal isn't for there to be a pool that fees are put into then distributed, it's to automatically give a portion of all smart contract invocations to the developer/team.


@e99243506bigplay 
> And, you earned one cent, then someone or groups lose that one cent. think about where the $$$ origin from.
Currently fees are being burned, but potentially fees will be split: https://github.com/aptos-foundation/AIPs/issues/23. I don't really understand the *origin* money argument, as the gas will be spent one way or another. Why not make it productive rather than burning it?

**Comment by e99243506bigplay** [comment]
> Hey @davidiw, thanks for your feedback!
> 
> > If I don't have any 3rd party contracts, what happens to funds not distributed to other purposes or burned?
> 
> I'm not sure I understand what you're saying here. If you don't have a deployed smart contract, why would you receive a portion of the fee sharing?
> 
> > For this to be fair, we'd need weighting based upon how much work done? Or complexity? What dictates that?
> 
> Complexity and work is already calculated when gas is calculated, isn't it?
> 
> > Does this incentivize less efficient coding paradigms to gain as much in return? The added complexity to the VM may have a non-negligible impact on performance.
> 
> I agree with this, that'd definitely be a concern.
> 
> > Copying a Move smart contract is trivial, what stops someone from evading this fee and just using their own?
> 
> That's a significant amount of overhead to bypass fees; indeed, deploying and copying a contract would likely cost more than just executing one.
> 
> > How much would a contractor stand to gain in this model? Are there smart contract developers that would prefer this? Part of my thinking was that you do open source development, so that when someone has a meaningful project, they hire you to help get them over the hump.
> 
> I don't see why a smart contract developer/team wouldn't want to receive additional fees. I'm not sure how fee sharing would conflict with smart contract developers being hired as contractors for development? I may not be understanding the argument you're making here.
> 
> The goal isn't for there to be a pool that fees are put into then distributed, it's to automatically give a portion of all smart contract invocations to the developer/team.
> 
> @e99243506bigplay
> 
> > And, you earned one cent, then someone or groups lose that one cent. think about where the $$$ origin from.
> 
> Currently fees are being burned, but potentially fees will be split: #23. I don't really understand the _origin_ money argument, as the gas will be spent one way or another. Why not make it productive rather than burning it? Can you expand further one why you consider it bad?

So, do 1 APT has value on it? How to exchange some APT on our hand to get some goods to meet our living needs? How $$$ is flowing to Aptos chain in?

**Comment by davidiw** [comment]
@dylanschultzie , this has been sitting around for quite a while, to repeat the concerns:
* There's a lot of concerns that need to be addressed, for example @e99243506bigplay brought up a great point on the fact that you can depend on my contract, I increase the complexity, and then I get a lot of gas rewards as a result.
* There's nothing stopping devs from copying each others contracts in Move, the bytecode is pretty useful, so library developers are less likely to make any proceeds.
* What is the right payment model? You mentioned just using the existing metering, that seems fine but it should be explicit.
* Gas rates on Aptos are basically 10^-6 APT, this doesn't seem like a worthwhile kickback for the amount of work to build this out.

So with that next steps: Any AIP needs a detailed proposal on how it would be implemented and what the broader ramifications for adopting the feature. For example, I think this proposal would likely result in less utility for shared smart contracts (or perhaps greater fear), add non-negligible performance overheads to transaction execution, and ultimately result in negligible payments to devs.

**Comment by dylanschultzie** [comment]
Hey @davidiw thank you for the reiteration - I agree that there could be further work here to iron out the concerns. Ultimately, I feel this proposal would be better suited towards a complete rework rather than a "massaging" to make it work. 

I'm happy to close this issue and go back to the drawing board.
