### ISSUE TITLE
[AIP-33][Block Gas Limit]

### ISSUE THREAD

**Issue by thepomeranian** [aptos-foundation/AIPs#132]
# AIP-33 - Block Gas Limit
  
## Summary

The per-block gas limit (or simply block gas limit) is a new feature that terminates block execution when the gas consumed by the committed prefix of transactions exceeds the block gas limit. This ensures that each block is executed within a predetermined limit of computational resources / time, thereby providing predictable latencies for latency-critical applications that involve even highly sequential and computationally heavy transactions.

Link to AIP: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-33.md

**Comment by Kuanishbek** [comment]
ddos attacks,,,,?

**Comment by danielxiangzl** [comment]
A malicious validator can always propose empty blocks, so this AIP does not introduce new attack vector.

**Comment by davidiw** [comment]
At worst case, a malicious validator can pollute a single round of consensus in which they are the proposer. Per what @danielxiangzl said this introduces no new attack vectors. Because the validator would be just as good not proposing any transactions at all.

**Comment by axelcazorla** [comment]
top !! bravo le gars !

**Comment by Kikimuzakki** [comment]
Ya, it was one of my quandary. But one thing that I fund is the gas is more descended since the first day.
