### ISSUE TITLE
[AIP-34][Unit Gas Price Estimation]

### ISSUE THREAD

**Issue by thepomeranian** [aptos-foundation/AIPs#134]
# AIP-34 - Unit Gas Price Estimation

## Motivation

Transactions are prioritized at mempool, consensus, and execution based on unit gas price — the price (in APT) that each transaction has committed to pay for each unit of gas. Clients need a way to estimate the unit gas price they should use to get a transaction executed on chain in a reasonable amount of time. This proposal contains a design where Aptos fullnodes provide an API to be used by clients for this purpose.

Link to AIP: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-34.md

**Comment by e99243506bigplay** [comment]
At current state on Aptos Chain, Please provide option to send transaction only on gas unit 100 in Petra Wallet, don't give suggestion gas price Please. it doesn't matter how much gas you pay in this low TPS environment.

**Comment by bchocho** [comment]
Thats correct, in this proposal we will reset to min unit gas price (100) when load is low.
