### ISSUE TITLE
[AIP-X][Discussion] Improve multisig v2 owner schema update flow

### ISSUE THREAD

**Issue by alnoki** [aptos-foundation/AIPs#156]
# Background

This AIP is being submitted per [the request](https://github.com/aptos-labs/aptos-core/pull/8525#pullrequestreview-1465158164) of @movekevin in https://github.com/aptos-labs/aptos-core/pull/8525

# Summary

Presently the multisig v2 Move APIs require multiple transactions for certain operations, which would be streamlined via abstraction and helper functions. https://github.com/aptos-labs/aptos-core/pull/8525 adds these functions.

# Motivation

Multisig v2 operations are already cumbersome compared with single-signer operations. Streamlining the process will lead to less friction for distributed governance solutions

# Specification

The following function signatures are proposed:

```move
    /// Like `create_with_owners`, but removes the calling account after creation.
    ///
    /// This is for creating a vanity multisig account from a bootstrapping account that should not
    /// be an owner after the vanity multisig address has been secured.
    public entry fun create_with_owners_then_remove_bootstrapper(
        bootstrapper: &signer,
        owners: vector<address>,
        num_signatures_required: u64,
        metadata_keys: vector<String>,
        metadata_values: vector<vector<u8>>,
    ) acquires MultisigAccount {

    /// Swap an owner in for an old one, without changing required signatures.
    entry fun swap_owner(
        multisig_account: &signer,
        to_swap_in: address,
        to_swap_out: address
    ) acquires MultisigAccount {

    /// Swap owners in and out, without changing required signatures.
    entry fun swap_owners(
        multisig_account: &signer,
        to_swap_in: vector<address>,
        to_swap_out: vector<address>
    ) acquires MultisigAccount {

    /// Swap owners in and out, updating number of required signatures.
    entry fun swap_owners_and_update_signatures_required(
        multisig_account: &signer,
        new_owners: vector<address>,
        owners_to_remove: vector<address>,
        new_num_signatures_required: u64
    ) acquires MultisigAccount {

    /// Add new owners, remove owners to remove, update signatures required.
    fun update_owner_schema(
        multisig_address: address,
        new_owners: vector<address>,
        owners_to_remove: vector<address>,
        optional_new_num_signatures_required: Option<u64>,
    ) acquires MultisigAccount {
```

The final function is an abstraction that can be substituted for existing owner modification functions.

# Alternatives

Do nothing, thus enforcing transactional complexity

# Reference implementation

https://github.com/aptos-labs/aptos-core/pull/8525

# Risks and drawbacks

Smart contract risk

**Comment by movekevin** [comment]
@alnoki Thanks for getting this kickstarted! Could you follow the template in https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-36.md? We don't need all the sections filled out but probably mainly the specs section as this introduces a few new functions :)

**Comment by alnoki** [comment]
> @alnoki Thanks for getting this kickstarted! Could you follow the template in https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-36.md? We don't need all the sections filled out but probably mainly the specs section as this introduces a few new functions :)

@movekevin I've updated the original comment per your request

**Comment by alnoki** [comment]
@movekevin per the closure of https://github.com/aptos-labs/aptos-core/pull/8525, shall I close this AIP?

**Comment by alnoki** [comment]
Closing per https://github.com/aptos-labs/aptos-core/pull/8525
