### ISSUE TITLE
[AIP-41][Discussion] Move APIs for public randomness generation

### ISSUE THREAD

**Issue by alinush** [aptos-foundation/AIPs#185]
**Note:** The [current v1.2 version of AIP-41 is here](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-41.md).

# Short summary

This AIP proposes a new Move module called `aptos_std::randomness` which enables smart contracts to **easily** and **securely** generate publicly-verifiable randomness.

The proposed `randomness` module leverages an underlying _on-chain cryptographic randomness implementation_ run by the Aptos validators. This implementation, however, is **outside the scope** of this AIP and will be the focus of a different, future AIP.

The only thing this AIP does assume of the _on-chain randomness_ is that it is **unbiasable** and **unpredictable**, even by a malicious minority of the validators (as weighed by stake).

## Proposed API (last updated August 11th, 2023)

```rust
module aptos_std::randomness {
    use std::vector;
  
    /// Generates `n` bytes uniformly at random.
    public fun bytes(n: u64): vector<u8> { /* ... */ }

    /// Generates a number uniformly at random.
    public fun u64_integer(): u64 { /* ... */ }
    public fun u256_integer(): u256 { /* ... */ }

    /// Generates a number $n \in [min_incl, max_excl)$ uniformly at random.
    public fun u64_range(min_incl: u64, max_excl: u64): u64 { /* ... */ }
    public fun u256_range(min_incl: u256, max_excl: u256): u256 { /* ... */ }

    /* Similar methods for u8, u16, u32, u64, and u128. */

    /// Generate a permutation of `[0, 1, ..., n-1]` uniformly at random.
    public fun permutation(n: u64): vector<u64> { /* ... */ }

    #[test_only]
    /// Test-only function to set the entropy in the RNG to a specific value, which is useful for
    /// testing.
    public fun set_seed(seed: vector<u8>) { /* ... */ }

    //
    // More functions can be added here to support other randomness generations operations
    //
}
```

**Comment by JacobADevore** [comment]
Hey @alinush, would love to connect and help give insights here.

**Comment by alilloig** [comment]
@JacobADevore according to the AIP document...
'''
Suggested implementation timeline
Describe how long you expect the implementation effort to take, perhaps splitting it up into stages or milestones.

This AIP is strictly about the proposed API, and not its implementation.
'''

So this is mostly just about the methods the module will expose, rather than about how the random generation will be done
'''
    /// Generates different randomness based on the given seed and the calling contract's address.
    public fun generate<T>(seed: &T): Randomness { /* ... */ }

    /// Amplifies the generated randomness object into multiple objects.
    public fun amplify(r: Randomness, n: u64): vector<Randomness> { /* ... */ }

    /// Consumes a `Randomness` object so as to securely generate a random integer $n \in [min_incl, max_excl)$
    public fun number(r: Randomness, min_incl: u64, max_excl: u64): u64 { /* ... */ }

    /// Consumes a `Randomness` object so as to securely pick a random element from a vector.
    public fun pick<T>(r: Randomness, vec: &vector<T>): &T { /* ... */ }
'''

cheers!

**Comment by alinush** [comment]
Really appreciate you folks taking a close look at this!

Indeed, as you can see, the current AIP status is `Draft`, which means I still need to finish writing it & explain things a little bit better 😋 ...

But @alilloig is right: this AIP **assumes** an underlying on-chain randomness implementation (e.g., the validators run some randomness beacon protocol; [pick your favorite!](https://eprint.iacr.org/2023/728)) and **focuses** on what the exposed API to Move developers should look like.

In that sense, the `generate()` function takes a `seed` so as to allow developers to generate multiple `Randomness` objects using different seeds (e.g., by carefully hashing the on-chain randomness with the BCS serialization of the seed).

However, as I type this, I wonder whether we should get rid of this `seed` argument and simply rely on calls to `amplify` to generate more pieces of `Randomness`.

**Comment by alilloig** [comment]
@alinush you are probably right, as a smart contract developer I don't really care from what seed my random numbers come from, just care about having access to them in the simplest possible way

**Comment by alinush** [comment]
Indeed. And using external randomness, as we explored in this [drand-based lottery example](https://github.com/aptos-labs/aptos-core/tree/ad3b32a7686549b567deb339296749b10a9e4e0e/aptos-move/move-examples/drand/sources), is quite awkward to (1) implement by developers and (2) to audit by external entities due to subtle timing assumptions.

**Comment by JacobADevore** [comment]
Understood, I appreciate you clearing that up for me.

What do you think of exchanging `seeds` for `amount` allowing a user to essentially call random(X) and get back a vector of X elements of randomness? (upper and lower bound for generation) Something like this would be great for DX (developer experience). To achieve X elements of randomness you could use a nonce starting at zero and incrementing for each randomness generated. With a nonce implementation, you might want to use an avalanche effect hashing algorithm though. 

Just a few thoughts. I would love to hear what you guys think.

**Comment by alinush** [comment]
That's an interesting idea! 

Would you still keep `amplify`? If so, could there be confusion on which API to use to generate multiple pieces of `Randomness`: i.e., one call to `generate(n)` vs. one call to `generate(1)` followed by an `amplify(n)`.

Either way, I like the idea of removing the seed and relying on amplifying the randomness as the **unique** way of generating multiple pieces of randomness.

Another possible simplification could be the use of a `RandomnessStream` object that you can call `next()` on, rather than the `amplify(n)`-based design which requires fixing `n` as an input.

I've actually just updated the AIP. You can find it [here](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-41.md). It should now be fully-contained.

I'm curious about the open question **O1** there, on how to deal with repeated calls to `generate` across the same TXN (whether seeded, unseeded or with an `n` parameter like you suggested).

**Comment by alinush** [comment]
I've actually just updated the AIP. You can find it [here](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-41.md). It should now be fully-contained.

I'm curious about the open question **O1** there, on how to deal with repeated calls to `generate` across the same TXN (whether seeded, unseeded or with an `n` parameter like you suggested).

**Comment by JacobADevore** [comment]
Very well written AIP @alinush!

**Comment by JacobADevore** [comment]
I wouldn't be opposed to either or, I would say allowing the user to generate within a loop is valuable from a DX perspective but I do see the risks from a security perspective. Maybe we can get some more insights from the Aptos team with this specific question at hand.

**Comment by alinush** [comment]
When you say "generate within a loop", do you assume the option(c) `generate` design which returns different results every time?

**Comment by MoonShiesty** [comment]
`number` and `pick` are trivial functions and should be inline

what is the motivation behind making `Randomness` non-copyable? I can imagine cases where modules might want to reuse the same source of randomness for multiple operations.

**Comment by alinush** [comment]
Thank you @banool and @MoonShiesty!

@MoonShiesty, the motivation was to prevent developers from accidentally generating identical randomness for two different events. Note that reusing the randomness is still possible but must be made explicit: i.e., once the `Randomness` object has been consumed into, say, an integer, that integer can be explicitly copied.

However, I think this  this `Randomness`-object-based API is not too great.

So I've just pushed [a PR](https://github.com/aptos-foundation/AIPs/pull/214/files) to move away from it and more towards a Rust-like RNG API.

Until it merges, you can see the [new API here](https://github.com/aptos-foundation/AIPs/blob/c31935acf85c341d36d9b386e68d773a0ffee0a8/aips/aip-41.md#risks-and-drawbacks).

**Comment by alinush** [comment]
@banool regarding why `aptos_std`, good question! It could live in `aptos_framework` too, I suppose. I'll keep track of that as an open question.

**Comment by banool** [comment]
What is the purpose of the generic type param on the `rng` method?
```
public fun rng<T>(): RandomNumberGenerator
```

**Comment by alinush** [comment]
> What is the purpose of the generic type param on the `rng` method?
> 
> ```
> 
> public fun rng<T>(): RandomNumberGenerator
> 
> ```

Ugh. That... is a typo. Thank you!

**Comment by alinush** [comment]
**Updated the AIP:** Added a test-only function to set the seed (entropy) of the RNG during testing, which should be useful for reproducing bugs:

```
    /// Test-only function to set the entropy in the RNG to a specific value, which is useful for
    /// testing.
    #[test_only]
    public fun set_seed(seed: vector<u8>);
```

**Comment by zjma** [comment]
```
    /// Returns an RNG for the current TXN and calling Move module. Repeated calls to this function 
    /// ...
    public fun rng(): RandomNumberGenerator { /* ... */ }
```

why does calling module matter? Could TXN be enough?

**Comment by junkil-park** [comment]
What is the purpose of exposing `RandomNumberGenerator` to users? What could go wrong if we hide it like:
```
fun rng(): RandomNumberGenerator { /* ... */ } // became private
/// Generates a number uniformly at random.
public fun u64(): u64 { let r = rng(); /* ... */ } // the RNG parameter is removed, but retrieved inside of the function
```

**Comment by alinush** [comment]
> ```
>     /// Returns an RNG for the current TXN and calling Move module. Repeated calls to this function 
>     /// ...
>     public fun rng(): RandomNumberGenerator { /* ... */ }
> ```
> 
> why does calling module matter? Could TXN be enough?

I don't think it does. I think what's more important is that each time an RNG is created via a call to `rng()` that the RNG be uniquely-seeded. This could be done by taking into context the calling module & the TXN hash. But in that sense, I think you are right: the TXN hash, which should be unique, should be enough.

**Comment by alinush** [comment]
> 

I think you're right: I don't see anything wrong with that approach either. 

It seems to lead to an even easier-to-use `randomness` module.

**Comment by zjma** [comment]
> > ```
> >     /// Returns an RNG for the current TXN and calling Move module. Repeated calls to this function 
> >     /// ...
> >     public fun rng(): RandomNumberGenerator { /* ... */ }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > why does calling module matter? Could TXN be enough?
> 
> I don't think it does. I think what's more important is that each time an RNG is created via a call to `rng()` that the RNG be uniquely-seeded. This could be done by taking into context the calling module & the TXN hash. But in that sense, I think you are right: the TXN hash, which should be unique, should be enough.
> 
> I was a bit worried that TXN hashes might not actually be unique due to a scare I once had with Bitcoin TXNs, where coinbase TXNs could actually have the same hash. So it might be worth mitigating against such (current or future) surprises in our design.

i was thinking that it's possible to mix in `(block-id, in-block-txn-position)` to ensure uniqueness?

**Comment by alinush** [comment]
PSA: AIP-41 has recently been updated to v1.2. The major changes are further simplifications to the API and countermeasures against so-called "test-and-abort" attacks.

See [changelog here](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-41.md#changelog).

**Comment by zjma** [comment]
In the lottery example, it's mentioned that any one can submit the txn to pay some gas and reveal the winner. But are they incentivized to do so?

Somehow Drand-based lottery can be designed to avoid this problem: the winner knows they are the winner, and are incentivized to claim the reward.

**Comment by alinush** [comment]
> In the lottery example, it's mentioned that any one can submit the txn to pay some gas and reveal the winner. But are they incentivized to do so?
> 
> Somehow Drand-based lottery can be designed to avoid this problem: the winner knows they are the winner, and are incentivized to claim the reward.

That's a good point. They are not. But this is just the simplest example I could come up with.

I guess we can change the code to send a small chunk of the winnings to the caller of `decide_winners`? So as to (1) pay for their TXN fees and (2) incentivize players to submit it?

**Comment by zjma** [comment]
> > In the lottery example, it's mentioned that any one can submit the txn to pay some gas and reveal the winner. But are they incentivized to do so?
> > Somehow Drand-based lottery can be designed to avoid this problem: the winner knows they are the winner, and are incentivized to claim the reward.
> 
> That's a good point. The caller of `decide_winners` is not incentivized. But this is only the simplest example I could come up with.
> 
> I guess we can change the code to send a small chunk of the winnings to the caller of `decide_winners`? So as to (1) pay for their TXN fees and (2) incentivize players to submit it?
> 
> (For this, we'd have to pass in a `signer` as an arg to `decide_winners` and `decide_winners_internal`, which is doable.)

I agree that DApp developers can fill the gap in their app-specific way.

I guess I'm more wondering how many dapps may benefit from drand style more than on-chain style. Also how many existing things need to be changed. One thing I can think of is that Petra wallet will no longer be able to show the balance diff preview before user click "sign".

**Comment by alinush** [comment]
I think it would be nice to have an API standard for verifying off-chain secure randomness & it would have the advantages you mention. However, due to the plethora of off-chain randomness beacons (e.g., drand, SupraOracles, Chainlink, etc) that is probably best done as a separate effort in its own AIP.

**Comment by chrisyy2003** [comment]
I would like to ask the `on-chain cryptographic randomness implementation run by the Aptos validators` is it already implemented?

**Comment by alinush** [comment]
Nope, not yet!
