### ISSUE TITLE
[AIP-42][Discussion] Aptos TypeScript SDK V2

### ISSUE THREAD

**Issue by 0xmaayan** [aptos-foundation/AIPs#193]
# AIP Discussion

This AIP introduces the development of a new version for the Aptos TypeScript SDK.

# Motivation

We have embarked on the development of a new version for our TS SDK due to several significant issues that have been identified in the current version. The current version suffers from problems with its overall structure and design, which has hindered the efficiency and effectiveness of its usage. Moreover, there have been inconsistencies in the naming conventions and types used within the SDK, leading to confusion and decreased productivity among developers. Furthermore, the existing SDK client support lack of customization, limited support for advanced client features and making debugging and troubleshooting more challenging.

Ultimately, these issues have collectively resulted in a less than optimal development experience for our users. Therefore, the new version of the SDK aims to address these problems and provide an improved, streamlined, and more user-friendly development experience for developers.

Read more about it here: [https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-42.md](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-42.md)

**Comment by kinrokinro** [comment]
![image](https://github.com/aptos-foundation/AIPs/assets/3493914/e981ffcf-dc93-49fd-9692-d3e9e6799604)
Looks like you missed the second point.

Looks great to me, but probably there should be backward compatibility where is it possible (there is no problem to use an old version for someone who will not needed an update overall, but...).

**Comment by kinrokinro** [comment]
And will be there a significant changes in the `aptos-wallet-adapter` because of this upgrade? We are using the adapter in our staking portal so won't miss something important.

**Comment by magnum6actual** [comment]
Types are currently a pain.  Had to jump through lots of hoops to build functions around constructing BCS transactions because half the types we need aren't exported.  This would be a very welcome change.

**Comment by 0xmaayan** [comment]
> ![image](https://user-images.githubusercontent.com/3493914/252494054-e981ffcf-dc93-49fd-9692-d3e9e6799604.png) Looks like you missed the second point.
> 
> Looks great to me, but probably there should be backward compatibility where is it possible (there is no problem to use an old version for someone who will not needed an update overall, but...).

Thanks, just updated the numbers =) 
Most of the changes are design and type changes and by nature it would be hard to have a backward compatibility, but version `^1.x.x` will always be here for anyone who prefer not to update.

**Comment by 0xmaayan** [comment]
> Types are currently a pain. Had to jump through lots of hoops to build functions around constructing BCS transactions because half the types we need aren't exported. This would be a very welcome change.

Thanks! Would be great to hear more about this issue and what types you need that aren't exported for you

**Comment by SamuelQZQ** [comment]
I believe it's valuable to add type-safe features from [@ThalaLabs/Surf](https://github.com/ThalaLabs/surf) into the V2 SDK. So that users can get end-to-end type-safety when interacting with smart contract.

We can add it in a flexible way, by adding some utility functions to provide the type-safety. And those type-safety could be optional for SDK users. Use `view` function as example:
```TypeScript
// You can still use the SDK in the original way, without type-safety
const payload = {
    function: "0x1::coin::balance",
    arguments: [],
    type_arguments: ['0x1::aptos_coin::AptosCoin'],
};

const result = client.view(payload);

// or you can use the new utility function leverage from Surf to get type-safety
const payload = createViewPayload(COIN_ABI, { // you should provide an ABI to enable the type inference
    function: "0x1::coin::balance", // if input a function not exist in the smart contract, you will get a build error.
    arguments: [], // if input wrong type of arguments, you will get a build error
    type_arguments: ['0x1::aptos_coin::AptosCoin'], // if input wrong number of arguments, you will get a build error
});

const result = client.view(payload); // the result also has the exact type, it's `[string]` here. Read a value out of range like `result[1]` will get a build error.
```

Please notice no matter the user want the type-safety or not, they will always use the `client.view`. No need to add additional interface like `client.viewWithTypeSafe` into the `AptosClient`. Clean and elegant.

For entry function, similarly, we can add a `createEntryPayload`. We can even help user doing the BCS encoding inside the `createEntryPayload`(Surf is already implemented in this way). So users no need to care about those complex BCS encodings.

We can also adding a `useABI` interface for the `AptosClient`.
```TypeScript
const coinClient = client.useABI(COIN_ABI);
coinClient.view.balance(...);
coinClient.entry.transfer(...);
```

Those `balance` and `transfer` functions internally still route to the `client.view` and `client.submitTransaction` in `AptosClient`.

With this approach, we adding optional type-safe features without breaking the original SDK convention. And those new type-safe interfaces would internally call the core functions from `AptosClient`, which means most of the logic is shared.

Just some rough idea. Any feedback or thoughts are appreciated.

**Comment by alnoki** [comment]
> I believe it's valuable to add type-safe features from [@ThalaLabs/Surf](https://github.com/ThalaLabs/surf) into the V2 SDK. So that users can get end-to-end type-safety when interacting with smart contract.

@SamuelQZQ @movekevin @banool I endorse this proposal

**Comment by 0xmaayan** [comment]
```
// you should provide an ABI to enable the type inference
```
@SamuelQZQ how one gets the ABI? The SDK supports fetching remote ABI (currently, uses it to serialize the payload arguments), I wonder if we can utilize this process with your implementation suggestion.

**Comment by SamuelQZQ** [comment]
> ```
> // you should provide an ABI to enable the type inference
> ```
> 
> @SamuelQZQ how one gets the ABI? The SDK supports fetching remote ABI (currently, uses it to serialize the payload arguments), I wonder if we can utilize this process with your implementation suggestion.

@0xmaayan Unfortunately, those linting, auto-completion, type-checking are build/compiling time features. But fetching remote ABI in current SDK happens at runtime. So user must manually add the ABI JSON, they can get from the Aptos Explorer.

**Comment by MartianAbhishek** [comment]
How are we structuring parameters? I would prefer to pass single object as an argument which gives more control over passing individual values and adding new parameter.

For example:
In current SDK method we pass 

```
async getEventsByEventHandle(
    address,
    eventHandleStruct,
    fieldName,
    query
)
```

We can change this to

```
async getEventsByEventHandle(args) {
    const { address, eventHandleStruct, fieldName, query } = args;
}
```

**Comment by 0xmaayan** [comment]
> How are we structuring parameters? I would prefer to pass single object as an argument which gives more control over passing individual values and adding new parameter.
> 
> For example: In current SDK method we pass
> 
> ```
> async getEventsByEventHandle(
>     address,
>     eventHandleStruct,
>     fieldName,
>     query
> )
> ```
> 
> We can change this to
> 
> ```
> async getEventsByEventHandle(args) {
>     const { address, eventHandleStruct, fieldName, query } = args;
> }
> ```

agreed. we should probably have a type for `args` so users would know what props need to be passed in, similar to what we have [here](https://github.com/aptos-labs/aptos-core/blob/3c8fd29a0f12d3186810afab9368b0393f2e0870/ecosystem/typescript/sdk/src/plugins/aptos_token.ts#L522) 
```
async getEventsByEventHandle(args: GetEventsByEventHandleType) {
    const { address, eventHandleStruct, fieldName, query } = args;
}
```

**Comment by Manahip** [comment]
might be a good time to replace `instanceof` with a `kind` system: https://github.com/aptos-labs/aptos-core/issues/5820
