### ISSUE TITLE
[AIP-2][Discussion] Multiple Token Changes

### ISSUE THREAD

**Issue by areshand** [aptos-foundation/AIPs#2]
**Summary**

This proposal contains the following changes:

1. token `CollectionData` mutation functions: provide set functions to mutate the TokenData fields based on the token mutability setting. 
2. token `TokenData` metadata mutation functions: provide set functions to mutate the CollectionData fields based on collection mutability setting. 
3. A bug fix for collection supply underflow: fix a bug that cause underflow error when burning unlimited collection’s TokenData.
4. Fix the order of events: when minting token, the deposit events enter queue before the mint events. This changes corrects the order to make the token deposit event after the mint event. 
5. Make a public entry for transfer with opt-in: provide an entry function to allow transfer token directly when users opt-in direct transfer.
6. Ensure royalty numerator is smaller than denominator: we observe about 0.004% token having a royalty > 100%. This change introduces an assertion to ensure royalty is always smaller or equal to 100%. 

**Motivation**

Change 1, 2:  the motivation is to support `CollectionData` and `TokenData` mutation based on the mutability config so that creators can update the fields based on their own application logic to support new product features

Change 3,4: the motivation is fix existing issues to make the token contract works correctly

Change 5: this motivation is to allow the dapp to directly call the function without deploying their own contracts or scripts

Change 6: this is to prevent potential malicious token that could lead to charging a higher fee than the token price. 

**Rationale**

Change 1, 2 are fulling existing token standard specification without introducing new functionalities

Change 3, 4, 5 and 6 are small fix and straightforward changes. 

**Reference Implementation**

The PRs of the changes above are listed below: 

Change 1, 2: 
https://github.com/aptos-labs/aptos-core/pull/5382
https://github.com/aptos-labs/aptos-core/pull/5265
https://github.com/aptos-labs/aptos-core/pull/5017

Change 3: https://github.com/aptos-labs/aptos-core/pull/5096

Change 4: https://github.com/aptos-labs/aptos-core/pull/5499

Change 5: https://github.com/aptos-labs/aptos-core/pull/4930

Change 6: https://github.com/aptos-labs/aptos-core/pull/5444

**Risks and Drawbacks**

Change 1, 2 are internally reviewed and undergo auditing to fully vet the risks

Change 3, 4 and 6 are to reduce the identified risks and drawbacks

Change 5 is to improve usability. This change doesn’t introduce new functionality

**Timeline**
Reference implementation changes will be deployed in devnet on 11/14 (PST) for ease of testing and providing feedback/discussion.
This AIP will be open for public comments until 11/17.
After discussion, reference implementation changes will be deployed in testnet on 11/17 for testing.

**Comment by sherry-x** [comment]
This AIP has been reviewed by @sherry-x @aching @davidiw @movekevin . The conclusion is to deploy it to devnet, and open for community feedback.

**Comment by orhanba** [comment]
very nice

**Comment by COTOARAYA** [comment]
excelente y mejor integrar toda la informacion a la comunidad que hace el proyecto aun mas fuerte

**Comment by tie-creator** [comment]
This will greatly benefit Aptos

**Comment by Kusergit** [comment]
To describe in detail the motivation for the upgrade and what it fixes is very trainable for us

**Comment by OlyushaVibe** [comment]
i'm sure that this improves and changes is for better! I appritiate it

**Comment by VooDoo087** [comment]
That's the right decision.

**Comment by ElagabalxNode** [comment]
Let's do it

**Comment by mathiyarasu65** [comment]
Excellent.

**Comment by michelle-aptos** [comment]
AIP is executed: https://governance.aptosfoundation.org/proposal/4
