### ISSUE TITLE
[AIP-48][Discussion] Allow direct commission change vesting contract

### ISSUE THREAD

**Issue by movekevin** [aptos-foundation/AIPs#237]
# AIP Discussion

The commission rate cannot be directly changed for a vesting contract after it's been created.
Vesting contract owner can currently get around this by updating the operator and commission rate to a temporary
different operator address, and then change it back in order to only change the commission rate. This can lead to potential validator node downtime.
This proposes allowing the vesting contract owner to change the commission directly while keeping the same operator.

Read more about it here: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-48.md

**Comment by alnoki** [comment]
@movekevin any thoughts on post-hoc commision configuration serving as a rug pull of sorts?

If someone enters into a vesting contract it is typically under the presumption of fixed parameters, not as as subject to the unilateral authority of an executor

**Comment by junkil-park** [comment]
@alnoki , changing the operator address and commission percentage has been possible from the beginning, through `update_operator`. This specific AIP allows the admin to conveniently change the operator commission percentage. This has been a requested feature.
