### ISSUE TITLE
[AIP-49][Secp256k1 Ecdsa for Transaction Authentication]

### ISSUE THREAD

**Issue by davidiw** [aptos-foundation/AIPs#247]
# AIP Discussion

Despite our desire to see more diverse key algorithms supported in hardware cryptographic platforms, the primary Aptos key algorithm, Ed25519, has yet to be adopted broadly across the ecosystem. secp256k1 ECDSA remains the incumbent and is broadly supported. This AIP introduces support secp256k1 ECDSA as a transaction authenticator for Aptos.

## Summary
In Aptos, each transaction contains a transaction authenticator that includes a signature and a public key, while the transaction itself contains the sender of the transaction. To verify that a transaction is properly signed, the verifier validates that the public key verifies the signature across the transaction and that the hash of the public key is stored on-chain in a hashed form under the account. By completing this verification, the verifier can be certain that the owner of the account indeed authorizes this transaction. This AIP adds support for secp256k1 ECDSA for transaction authentication.

## Motivation
Many organizations already have support for secp256k1 Ecdsa but not Ed25519
Hardware crypto has not broadly adopted Ed25519 yet rmain compatible with secp256k1 ECDSA

Read more about it here: https://github.com/aptos-foundation/AIPs/pull/248

This AIP is related to [AIP-55 Generalize Transaction Authentication and Support Arbitrary K-of-N MultiKey Accounts](https://github.com/aptos-foundation/AIPs/issues/267)

**Comment by mtrackeros** [comment]
> # AIP Discussion
> 
> Despite our desire to see more diverse key algorithms supported in hardware cryptographic platforms, the primary Aptos key algorithm, Ed25519, has yet to be adopted broadly across the ecosystem. secp256k1 ECDSA remains the incumbent and is broadly supported. This AIP introduces support secp256k1 ECDSA as a transaction authenticator for Aptos.
> ## Summary
> 
> In Aptos, each transaction contains a transaction authenticator that includes a signature and a public key, while the transaction itself contains the sender of the transaction. To verify that a transaction is properly signed, the verifier validates that the public key verifies the signature across the transaction and that the hash of the public key is stored on-chain in a hashed form under the account. By completing this verification, the verifier can be certain that the owner of the account indeed authorizes this transaction. This AIP adds support for secp256k1 ECDSA for transaction authentication.
> ## Motivation
> 
> Many organizations already have support for secp256k1 Ecdsa but not Ed25519 Hardware crypto has not broadly adopted Ed25519 yet rmain compatible with secp256k1 ECDSA
> 
> Read more about it here: #248
> 
> This AIP is related to [AIP-55 Generalize Transaction Authentication and Support Arbitrary K-of-N MultiKey Accounts](https://github.com/aptos-foundation/AIPs/issues/267)
