### ISSUE TITLE
[AIP-50][Discussion] Change Commission rates in delegation pools

### ISSUE THREAD

**Issue by junkil-park** [aptos-foundation/AIPs#249]
# AIP Discussion

Currently, the commission rate is set by the pool owner at initiation of the pool. We propose allowing the pool owner to change the commission rate after delegation pool creation.

Read more about it here: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-50.md

**Comment by alinush** [comment]
This seems worrisome for users: they stake and now they have to be vigilant the pool doesn't increase its commission.

For decreases, its fine: users make more.

For increases, why can't the pool owner start a new pool with a new commission instead?
