### ISSUE TITLE
[AIP-52][Discussion] Automated Account Creation for Sponsored Transactions

### ISSUE THREAD

**Issue by davidiw** [aptos-foundation/AIPs#258]
This AIP proposes to allow sponsored transactions, one in which the gas payer is not the primary signer of the transaction, to create accounts for the primary signer if it does not exist. Currently when submitting a sponsored transaction an account must first exist. This is an unnecessary friction for using gas fee payer accounts for new accounts. As it means that the gas fee payer solution must first submit an independent transaction to the blockchain.

Read more about it here: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-52.md

**Comment by magnum6actual** [comment]
This is a great idea.  In our business model, we tend to mass onboard a large number of accounts at the same time when we index a new city/market for Nutrios.  Having to create several thousand accounts in rapid succession creates a sequence number bottle neck for our fee payer account.  This would resolve all of that of for us and would be a most welcomed addition.
