### ISSUE TITLE
[AIP-54][Discussion] Object code deployment

### ISSUE THREAD

**Issue by movekevin** [aptos-foundation/AIPs#259]
# AIP Discussion

This AIP proposes a simplified code deployment process that improves the current developer experience with deploying and upgrading Move modules on Aptos. Specifically:
1. Developers can deploy a package of Move modules, which get automatically get uploaded to a newly created object.
2. Developers receive a PublisherRef object if the package is upgradable.
3. PublisherRef can be used to update the package in the future and transferred freely to another account.

This new simplified and improved code deployment process will eliminate most of the current pains and confusion around code deployment.
Furthermore, this will reduce the storage footprint of each code deployment while maintaining the ease of adding programmatic control over publishing/upgrading as it'd not need to create a new resource account.

Read more about it here: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-54.md

**Comment by e99243506bigplay** [comment]
Please consider about 700kb+ move bytecode package in the deployment in future.
