### ISSUE TITLE
[AIP-57][Discussion] Block Output Size Limit and Conflict-Aware Block Gas Limit

### ISSUE THREAD

**Issue by igor-aptos** [aptos-foundation/AIPs#285]
# AIP Discussion

This builds on top of [AIP-33](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-33.md), to improve latency predictability during arbitrary workload. It includes:

- adding block output limit, ending a block when predefined output size is reached.
- adding conflict-awareness to block gas limit.

As a consequence, information about whether block limit is reached would not be able to be infered onchain, so we are going to introduce a new type for StateCheckpoint transaction (i.e. replacing it with BlockEpilogue transaction), which will contain additional information

Read more about it here: [Link to AIP](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-57.md)

**Comment by alnoki** [comment]
@igor-aptos will the "conflict" coefficient be dynamic based on the other txns in the block? E.g. if I hit a global counter in a block where I'm the only txn that hits that counter, vs hitting the same counter in a block where *everyone* is hitting it (e.g. altcoin trade vs hot NFT mint)

Also, will this lower relative gas costs for parallelism-aware txns that succesfully isolate state into indedpendent channels (@davidiw )

How does this relate to the concept of "local fees", currently in exploration on Solana, where gas costs are railed for areas of state contention but lower elsewhere?
