### ISSUE TITLE
[AIP-58][Discussion] Gas Schedule Adjustments

### ISSUE THREAD

**Issue by igor-aptos** [aptos-foundation/AIPs#286]
# AIP Discussion

Current gas schedule doesn't correspond well with validator throughput. In perfect case, gas/s should be constant, for any workload.

We are going to take a set of representative workloads, run validator throughput benchmarks to measure their TPS, and then calibrate re-weighting 4 groups of charges to minimize square error against a target gas/s. Four groups of charges we will look at here will be intrinsic, execution, io-read and io-write.

Read more about it here: [Link to AIP](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-58.md)

**Comment by alnoki** [comment]
@igor-aptos does this address the discrepancy between timeouts and op costs per https://github.com/aptos-foundation/AIPs/issues/298#issuecomment-1901264751?

**Comment by igor-aptos** [comment]
@alnoki - this improves calibration, but not perfectly. further calibrations and more granular calibrations are planned, as explained in the other issue.
