### ISSUE TITLE
[AIP-61][Discussion] Keyless accounts

### ISSUE THREAD

**Issue by alinush** [aptos-foundation/AIPs#297]
# AIP Discussion

Currently, the only way[^multisig] to secure your Aptos account is to protect the **secret key (SK)** associated with it. Unfortunately, this is much easier said than done. In reality, secret keys are often *lost* (e.g., users forget to write down their mnemonic when first setting up their Aptos wallet) or *stolen* (e.g., users are tricked into revealing their SK). This makes onboarding users unnecessarily difficult and drives users away when their accounts are lost or stolen.

In this AIP, we describe a more user-friendly approach for account management that relies on the _unmodified_[^openpubkey] **OpenID Connect (OIDC)** standard and recent developments in **zero-knowledge proofs of knowledge (ZKPoKs)** of **OIDC signatures**[^snark-jwt-verify]$^,$[^nozee]$^,$[^bonsay-pay]$^,$[^zk-blind]$^,$[^zklogin].

Specifically, we enable **keyless accounts** on Aptos that are secured through the owner’s existing **OIDC account** (i.e., their Web2 account with an **OIDC provider** such as Google, GitHub or Apple), rather than through a difficult-to-manage secret key. In a nutshell, _“your blockchain account = your OIDC account”_.

An important property of keyless accounts is that they are not only *bound* to the user’s OIDC account (e.g., `alice@gmail.com`) but are also bound to a **managing application** registered with the OIDC provider (e.g., a dapp’s `dapp.xyz` website, or a wallet’s mobile phone app). In other words, they are **application-specific** accounts. As a consequence, if the managing application of an account disappears or loses their OIDC provider registration credentials, then users whose accounts are bound to this application will become inaccessible, unless alternative **recovery paths** are provided (discussed below).

Read more about it here:
 - Full AIP-61 text : https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-61.md
 - [AIP PR](https://github.com/aptos-foundation/AIPs/pull/296/files)

[^bonsay-pay]: https://www.risczero.com/news/bonsai-pay
[^multisig]: There are alternatives to single-SK accounts, such as multisignature-based accounts (e.g., via [MultiEd25519](https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-stdlib/sources/cryptography/multi_ed25519.move) or via [AIP-55](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-55.md)), but they still bottle down to one or more users protecting their secret keys from loss or theft.
[^nozee]: https://github.com/sehyunc/nozee
[^snark-jwt-verify]: https://github.com/TheFrozenFire/snark-jwt-verify/tree/master
[^zk-blind]: https://github.com/emmaguo13/zk-blind
[^zklogin]: https://docs.sui.io/concepts/cryptography/zklogin

**Comment by davidiw** [comment]
* Under security, this link is broken: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-61.md#Security,-Liveness-and-Privacy-Considerations -- didn't dig into figure out why
* A resolution to a lost service is to use alternative backups such as mnemonic based keys, multiple zklogins per account, or passkeys.... this is a unique selling point of Aptos which is not highlighted in the AIP.

**Comment by alinush** [comment]
- Fixed the typo
- Will add the 2nd bullet to my TODO

**Comment by alinush** [comment]
Hi @daoauth, sorry for the late response. We already support WebAuthn! See the AIP [here](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-66.md) and feel free to discuss [here](https://github.com/aptos-foundation/AIPs/issues/322).

**Comment by daoauth** [comment]
> I am a developer eager to see WebAuthn implemented in keyless as soon as possible. Although the AIP considers WebAuthn, the actual implementation only includes Ed25519. Could this be due to the support for secp256r1? Additionally, I would like to propose extensions for WebAuthn. Would it be appropriate to continue with this here, or should I create a new AIP? I believe WebAuthn is the key to unlocking the remaining potential of keyless accounts.

Thank you for the great news. I will actively use it.
