### ISSUE TITLE
[AIP-63][Discussion] Coin to Fungible Asset Migration

### ISSUE THREAD

**Issue by thepomeranian** [aptos-foundation/AIPs#326]
# AIP Discussion

# Summary
[AIP-21](https://github.com/lightmark/AIPs/blob/main/aips/aip-21.md) introduced fungible asset standard aiming to replace the old coin standard to represent any fungible asset on chain, including but not limited to coin. The evolving of Aptos ecosystem gradually necessitates the migration from coin framework to fungible asset framework for its superiority. This AIP aims to migrate migrating from coin to fungible asset in a seamless way that the impact to existing ecosystem projects and users is as small as possible.

This AIP proposes a global mapping between coin and fungible asset and allow coin module to treat paired coin and fungible asset interchangeably and facilitates the migration by converting CoinStore<CoinType> to the primary fungible store of the paired fungible asset whenever possible.

Read more about it here: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-63.md

**Comment by lightmark** [comment]
![WechatIMG31](https://github.com/aptos-foundation/AIPs/assets/1549573/40abfc25-2711-4ae0-ad43-d0a08013fe0f)
