### ISSUE TITLE
[AIP-X][Discussion] High-Performance Fixed Point Decimal Module for the Aptos Standard Library

### ISSUE THREAD

**Issue by alnoki** [aptos-foundation/AIPs#337]
# High-Performance Fixed Point Decimal Module for the Aptos Standard Library

## Background

Financial applications rely heavily on decimalized arithmetic implementations,
since currency uses a base-ten number system.

However, the Aptos Standard Library does not presently offer any decimal support
beyond what can be implemented using standard integers, and this gap in
functionality requires developers in some circumstances to develop custom
decimal libraries for their own applications.

In particular, fixed-point decimal applications are required for pricing of
assets with disparate market values, where a trade at current market prices may
involve several orders of magnitude discrepancy between the amount of subunits
on each side of the trade. More concretely, a suitable application needs enough
precision to represent the exchange price ($quote / base$) for both of the
following scenarios:

1. Buying 25 `Coin.value` of base asset A, paying 1,000,000,000,000 of quote
   asset B.
1. Selling 1,000,000,000,000 `Coin.value` of base asset C, receiving 25 of quote
   asset D.

Notably, the Aptos Standard Library already includes fixed-point functionality, however it:

1. Uses a radix of 2 and is thus is not suited for decimal-based financial
   applications.
1. Relies on a struct-based wrapper which adds gas costs for applications that
   rely on repetitive arithmetic operations.
1. Is lacking in inline functions or unchecked variants for enhanced performance
   in known safe scenarios.

Hence in this AIP I propose a high-performance fixed point decimal module for
the Aptos Standard Library, which includes the following:

1. Adequate precision to represent multiple orders of magnitude in decimal
   pricing.
1. Native integer representation for reduced gas costs.
1. Inline, unchecked functions for enhanced performance in known safe scenarios.

## Reference implementation

See https://github.com/aptos-labs/aptos-core/pull/11952

## Testing

Tested to 100% code coverage.

**Comment by davidiw** [comment]
Thanks for the contribution! Would love to see some interaction here to motivate pushing this forward. If you would like to submit a draft, we can also land that so we can keep historical revisions. In terms of moving forward, I'd love to see interest from other folks in the community.

**Comment by alnoki** [comment]
> Thanks for the contribution! Would love to see some interaction here to motivate pushing this forward. If you would like to submit a draft, we can also land that so we can keep historical revisions. In terms of moving forward, I'd love to see interest from other folks in the community.

@davidiw Thanks for the above, noting that there's already been some discussion on the reference implementation PR

I just added a failing test in https://github.com/aptos-labs/aptos-core/pull/11952/commits/9d4611ee2db2ae84cc9c6ee674ee5483dd132a79 to highlight some of the precision asks that @MoonShiesty put forth as far as using decimal fixed for conversion between amounts, and I would certainly appreciate more discussion on how to enable, using a fixed point multiplier, from any arbitrary `u64` to and other abritrary `u64`

Would it be appropriate to submit a AIP PR now or after more discussion?
