### ISSUE TITLE
[AIP-X][Discussion] Allocate places for Aptos Ru Community team to validate Aptos mainnet

### ISSUE THREAD

**Issue by V1017** [aptos-foundation/AIPs#34]
**Proposal/Solution** 

**Hello Aptos team and community** 
 
We represent the Aptos Ru Community team: one of the earliest, most active adopters, coordinators and contributors of Aptos across the Russian across Russian speaking universe. Our team includes both Aptos Moderators and Coordinators.

Among many other things we are creators of the following projects:
• Weekly RuWorkshop events/Ecosystem reviews
• AptosRuHub website
• Russian translation of Official Aptoslabs Medium
• Russian translation of Official Aptos Developer Documentation
• Step-by-step video guides how to launch Aptos node (from the earliest devnet up to Ait3)
• Telegram group with c. 2000 subscribers
• Weekly summaries of Move Mondays and Ru Workshops
 
And also our team helped to set up lots of nodes in DevNet and educated many people on Aptos
Each of us has proven himself from the best side and has a brilliant reputation in the community and on the Aptos discord server.
We are constantly working on community development, improving the quality of materials and events.

**Our objective
Grow the community by increasing its activity and size.**
 
**Limitation**
Lack of financial resources for the preparation of better quality materials (articles, videos, etc.), event marketing, attracting influencers, promotional gifts, giveaways, etc.,
 
**Proposal/solution**
Allocate places for Aptos Ru Community team to validate Aptos mainnet.
 
**This proposal allows to achieve the following:**
- accelerate the development of the Russian-speaking community
- improve decentralization of the Aptos network
 
Allocating places for validation would solve the problem of financing community project (Aptos Ru Community) and would be able to improve their quality and stimulate activity, since the rewards from network validation would not leave the project, but would be used to promote different activities and as the result speedup attraction/onboarding of users and builders to Aptos Network across Russian speaking audience.
 
Given our successful participation in all stages of the AIT as well as in validation activity in other projects, we have all the necessary experience to participate in Mainnet validation
 
We are Aptos Ru community team and we want to grow our community and help Aptos to engage new members and grow the whole Ru community.
 
**All our resources**
https://link3.to/aptosrucommunity
https://t.me/AptosRUcommunity
https://tiny.one/aptosruhub
https://youtube.com/@aptosrucommunity
https://t.me/AptosWorkshopRU
https://cr-nepos.gitbook.io/aptos-ru/
https://medium.com/@aptos-in-russian

**Comment by prisoner10** [comment]
aptos
it is future

**Comment by e99243506bigplay** [comment]
> Hi @V1017, you can submit an application here if you are interested in becoming a validator operator for Aptos mainnet: https://aptos.typeform.com/to/I1K6YVlX
> 
> AIPs are more for core development and operations related improvements to the network.
> 
> Thanks!

KYC of course.
