### ISSUE TITLE
[AIP-72][Discussion] Minting Standard for Digital Assets

### ISSUE THREAD

**Issue by jillxuu** [aptos-foundation/AIPs#370]
# AIP Discussion
This AIP introduces the development of a non-framework minting standard for digital assets.

# Motivation
This AIP focuses on introducing a non-framework standard for creating collections and tokens. Currently there is a simplistic, non-extensible no-code token solution `aptos_token`. This provides the basic use case of creating tokens and collections, but no customizations of how this is done, such as whitelists, coin payments with dynamic types. Several highlights of this AIP are:

1. Use objects to create collections and manage mints.
2. Generic standard which makes it amenable easily being indexed.
3. Take a modular approach where each module, including the mint functions, are completely standalone and can be used in conjunction with each other in the custom module.

Read more about it here: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-72.md

**Comment by rutraff** [comment]
nh
