### ISSUE TITLE
[AIP-73][Discussion] Dispatchable token standard

### ISSUE THREAD

**Issue by thepomeranian** [aptos-foundation/AIPs#374]
# AIP Discussion

## Summary
Right now the Aptos Framework defines one single fungible_asset.move as our fungible asset standard, making it hard for other developers to customize the logic they need. With this AIP, we hope that developers can define their custom way of withdrawing and deposit for their fungible asset, allowing for a much more extensible way of using our Aptos Framework.

Read more about it here: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-73.md

**Comment by alnoki** [comment]
# Compilation of my comments thus far from elsewhere

I've provided some commentary on this topic in several places but it's gotten disjointed so I'll start with a compilation of relevant posts, mostly in conversation with @davidiw and @runtian-zhou 

On https://github.com/aptos-labs/aptos-core/issues/12490:

1. https://github.com/aptos-labs/aptos-core/issues/12490#issuecomment-1995506633
2. https://github.com/aptos-labs/aptos-core/issues/12490#issuecomment-1995927506
3. https://github.com/aptos-labs/aptos-core/issues/12490#issuecomment-1998838538
4. https://github.com/aptos-labs/aptos-core/issues/12490#issuecomment-2053753779
5. https://github.com/aptos-labs/aptos-core/issues/12490#issuecomment-2057287832

On https://github.com/aptos-labs/aptos-core/pull/12635:
1. https://github.com/aptos-labs/aptos-core/pull/12635#pullrequestreview-1953751720
2. https://github.com/aptos-labs/aptos-core/pull/12635#issuecomment-2053754316


# Summary

Generally, I am concerned with how behaviors like tax on transfer will affect DeFi accounting and break correctness guarantees currently offered by existing standards. Generally, however, these concerns are alleviated so as as there exist two APIs related to transfers:

1. A transfer API that enforces a fixed amount is withdrawn from the sender
3. A transfer API that enforces a fixed amount is deposited to the receiver

# Questions on current implementation

Per Telegram discussion with @davidiw:

> Withdraw must withdraw exactly the expected amount from the users balance

Question 1. Is it correct to assume that this can be used in a transfer context with the condition `fixed amount is withdrawn from the sender`? 

> There's a dedicated deposit function `transfer_assert_minimum_deposit` for ensuring that a minimum is deposited.

Question 2. Could this be extended to for the case `transfer_assert_exact_deposit`?

**Comment by davidiw** [comment]
@alnoki ,
> Question 1. Is it correct to assume that this can be used in a transfer context with the condition fixed amount is withdrawn from the sender?

Yes. All calls to `withdraw` have the assertion on fixed amount withdrawn. Of course, that doesn't mean the output amount of `withdraw` is guaranteed.

> Question 2. Could this be extended for the case transfer_assert_exact_deposit, to meet the condition fixed amount is deposited to the receiver?

The window for the first release, 1.12, is likely missed. I think my concern here is that if there is any dynamics in the call, this may be hard to guarantee, while minimum is likely more easily guaranteed. We could add the API, but figured it would be good to discuss if both are needed.

**Comment by alnoki** [comment]
> We could add the API

@davidiw Please do! Looking forward to it :)

FYI one implementation could be a version that just uses the minimum deposit under the hood, and "refunds" any extra back to the sender

**Comment by davidiw** [comment]
> > We could add the API
> 
> @davidiw Please do! Looking forward to it :)
> 
> FYI one implementation could be a version that just uses the minimum deposit under the hood, and "refunds" any extra back to the sender

Ahh, this could be done, there's a tradeoff, of course, that the user could be double taxed... not sure that's better but maybe in some cases it is.

**Comment by alnoki** [comment]
>  that the user could be double taxed

@davidiw could this be avoided by doing some kind of forced direct transfer? E.g. in current implementation I've seen all kinds of admin-level permissions to do things like this, seems doable

Just flagging that for such a case then events should only be emitted after the refund
