### ISSUE TITLE
[AIP-75][Discussion] Prover service for keyless accounts

### ISSUE THREAD

**Issue by alinush** [aptos-foundation/AIPs#379]
# AIP Discussion

## Summary

This AIP is an extension of [AIP-61: Keyless Accounts](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-61.md), which allow users to have a wallet that is tied to an OpenID account, and to sign transactions for the blockchain via their OIDC provider, instead of via a secret key. As summarized in AIP-61, _“your blockchain account = your OIDC account”_. 

However, OpenID Connect authenticates users based on personally-identifying information (e.g., an email address or a Twitter handle). In this sense, are two privacy goals:

- The OpenID provider must **not** learn which wallet addresses are linked to which OpenID users.
- The validators (and other outside observers) also must **not** learn the link between wallet addresses and OpenID users.

To achieve privacy, a **zero-knowledge proof (ZKP)** is given by users to validators to authenticate transactions. Generating such a proof must be done each time a user logs in, and then each time the user's ephemeral public key expires[^spec], and is computationally intensive. To allow for users to log in quickly and on low-powered hardware, the proof computation must be offloaded to a **prover service**.

This AIP's focus will be the motivation, design and risks around this prover service.

Read more about it here: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-75.md

**Comment by e99243506bigplay** [comment]
awww I have no mathematical knowledge, I like to ask could we preserve a way to let user to prove it self, not just prover service. of course I understand prover service is for offload proof computation works, but more important I think is give user to choice which way better.

**Comment by alinush** [comment]
We are working on speeding up the underling zkSNARK in order to make client-side proof computation practical.

In that case, the prover service will no longer be needed.

Nonetheless, we may still rely on a "proof-checking service" to pre-validate user-computed proofs as a DoS prevention measure.
