### ISSUE TITLE
[AIP-77][Discussion] Multisig V2 Enhancement

### ISSUE THREAD

**Issue by thepomeranian** [aptos-foundation/AIPs#409]
# AIP Discussion

This AIP proposes to enhance the Multisig V2 by (1) limiting the maximum number of pending transactions, (2) introducing batch operation functions, and (3) implicitly voting on the transaction execution.

Read more about it here: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-77.md

**Comment by simqkevich** [comment]
Does Petra have a plans to implement multi-sig feature?

**Comment by junkil-park** [comment]
> Does Petra have a plans to implement multi-sig feature?

@simqkevich , there is an available wallet that supports the Aptos' multisig v2 standard. Please check out https://www.m-safe.io/aptos/home.
