### ISSUE TITLE
[AIP-82][Discussion] Transaction context extension

### ISSUE THREAD

**Issue by thepomeranian** [aptos-foundation/AIPs#420]
# AIP Discussion

## Summary

This AIP proposes an extension to the transaction context module within the Aptos Framework. The enhancement will enable users to retrieve user transaction information directly in smart contracts. This feature is crucial for supporting the mechanism that enables custom user prologues and epilogues, which will be addressed in a separate AIP later.

Read more about it here: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-82.md

**Comment by dinhtran0402** [comment]
test
