### ISSUE TITLE
[AIP-X][Canonical Image Templates for Token Collections]

### ISSUE THREAD

**Issue by SaulDope** [aptos-foundation/AIPs#432]
# AIP Discussion

In this document I propose a standard for Collection image templates on-chain. Alongside a Collection, a developer could store a `CollectionImageTemplate`, containing an SVG template and a list of keys. To render an SVG from this template for a token in the collection, a wallet would fetch the template and keys, then use the keys to fetch values from that token's PropertyMap. The wallet would then use a provided library to parse the SVG template using the now built PropertyMap. Token images could dynamically update based on the underlying data changing, unlocking a variety of usecases in DeFi, Ticketing, and more.

The current standard solution for images for tokens in a collection is to host them off-chain and point to them via uri. This is usually done with a CDN or via IPFS. This solution is brittle as the uri could break for many reasons: dns, cloud issues, lack of ipfs upkeep, etc. In an environment with easy perpetuity for logic and data (smart contracts), perpetuity for image hosting is still difficult. Additionally, storing thousands of uris on-chain takes a suprising amount of storage.

I aim to explain how a developer could store their template and property map values on each token, and how a wallet would render that token's image. I will also describe a variety of usecases.

Read more about it here: [AIP Link](https://github.com/aptos-foundation/AIPs/pull/431)

**Comment by JohnChangUK** [comment]
This is a great proposal, thanks a lot for putting this together!

Seems like the goal is to use and update property maps for the tokens, which wallets/UIs will read and update based on. this means updating the property maps every time an update needs to be made? Are there discussions on the trade offs worth making here? I.e. sending a TX to update a property vs not.

Also would love to incorporate this; as part of [AIP 72 digital asset standard](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-72.md), I think this would be great to incorporate into the [Token Minter](https://github.com/aptos-labs/token-minter) standard we have defined! The purpose of Token Minter is to improve the developer experience for creating and managing digital assets. Would love to work together to implement this in token minter and have this widely adopted.

**Comment by SaulDope** [comment]
Hey John,

Thanks for reading this over!

Regarding property map updates, ideally developers would design their token in such a way that transactions involving the token will update the property map as required, so that transactions purely to update the property map aren't required.  For example, with our position tokens on the mirage perps platform, we update the opening_price, fees_paid etc fields whenever you open your position or update the size/margin etc.  

I do think its worth considering more on if it would be possible to pipe in fields that _aren't_ on the property map.  For example, its not possible for us to include liquidation price in the property_map as that constantly changes based on how much outstanding funding fees a position owes (which is constantly changing).  In an ideal world, there would be a generic function on a collection that returns a map of keys - values for a specific token to be used to populate the template.  This way you could use whatever data you wanted.  However, I do not think this is necessary for v1 of this idea.

Definitely agree on the base_uri concept.  I was shocked at how much space storing URIs can take.  By keeping the base_uri in the same place as the template, you can check both "secondary" image methods with one borrow.  The object might need a slight name change for those using it purely for base_uri though.

It would be great to collaborate on AIP-72!  I've reached out offline to discuss about how I can contribute.

**Comment by thepomeranian** [comment]
closing since the convo has moved

**Comment by SaulDope** [comment]
Won't it be more difficult for people to locate the proposal if it is not in the official AIP issues?
