### ISSUE TITLE
[AIP-101][Discussion] Safe onchain key rotation address mapping for standard accounts

### ISSUE THREAD

**Issue by thepomeranian** [aptos-foundation/AIPs#515]
# AIP Discussion

## Summary

The onchain key rotation address mapping has functional issues which inhibit
safe mapping of authentication key to originating address for standard accounts.
This proposal resolves these issues by adding assorted checks and extra function logic.

Read more about it here: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-101.md

**Comment by igor-aptos** [comment]
Thank you for the design review, these changes look sound, I vote for "approve".

On the broader question, this raises valid concerns about `OriginatingAddress`, some of which are not resoled by the above, as noted. 
As main use is for being able to figure out account address(es) from a given auth key, I think more general and canonical way is to index `Account.authentication_key` => list of account addresses, and provide API to query it. Given that, it seems like there might not be need for having `OriginatingAddress` onchain at all.
