### ISSUE TITLE
AIP template issues

### ISSUE THREAD

**Issue by alinush** [aptos-foundation/AIPs#58]
The YAML header does not contain documentation for the following fields and their format:

 - `created` -> Explain what this is and its appropriate (date?) format.
 - `last-call-end-date` -> Explain what this is and its appropriate (date?) format.

Furthermore, for the `aip` field, it says _"(this is determined by the AIP Manager)"_. However, one would expect to just put the AIP # here. So please clarify if this should be entered by the user (and what should be entered), or if it should be left blank. "Determined by the AIP manager" does not clarify if I need to enter anything there :)

**Comment by sherry-x** [comment]
Thanks for the feedback! we will address this. When first time drafting the aip you can leave the number empty (name your file with some other temporary name, e.g. hash-functions.md) we will assign number during AIP review meeting, to make sure there's no collision and not assign number to not-so-ready AIPs.

**Comment by sherry-x** [comment]
Template updated. Please let us know if you have more questions. Thank you!
