### ISSUE TITLE
Please drop the gas unit price to 0.00000010 or 0.00000001

### ISSUE THREAD

**Issue by e99243506bigplay** [aptos-foundation/AIPs#6]
by that, I think Aptos chain will more active and incentive people to action in chain.
For example, about currently Souffl3 Bake-off event if do bake once, we must pay 0.06 APT gas fee to do it.

**Comment by areshand** [comment]
> by that, I think Aptos chain will more active and incentive people to action in chain. For example, about currently Souffl3 Bake-off event if do bake once, we must pay 0.06 APT gas fee to do it.
we will follow up more to understand more why the bake-off gas fee is high.

**Comment by davidiw** [comment]
We're working on this plan now: https://medium.com/aptoslabs/the-path-to-10x-lower-gas-fees-on-aptos-with-community-driven-feedback-7cca875a513f

**Comment by e99243506bigplay** [comment]
> We're working on this plan now: https://medium.com/aptoslabs/the-path-to-10x-lower-gas-fees-on-aptos-with-community-driven-feedback-7cca875a513f

Gas-efficient data structures do not exists on this moment, if want be gas efficient, then must do not use Table or Vector, only using global storage operators like `move_from` `move_to` `borrow_global_mut` `borrow_global` , or create a low gas meter count data structure to fit our use.

if going to use global storage operators, then next has be hack the generic parameter, think it about what parameter combination to fit our situation need for the gas optimization.

**Comment by davidiw** [comment]
Please take a look at 

https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-9-Resource%20Groups.md
https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/move-examples/data_structures/sources/smart_vector.move

Resource groups need approval from both the AIP committee and governance, but are code complete.
Smart Vector is largely code complete but need an AIP.

**Comment by e99243506bigplay** [comment]
> Please take a look at
> 
> https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-9-Resource%20Groups.md https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/move-examples/data_structures/sources/smart_vector.move
> 
> Resource groups need approval from both the AIP committee and governance, but are code complete. Smart Vector is largely code complete but need an AIP.
> 
> We also are nearly complete with refunds and will begin work in earnest on splitting storage and execution gas fees.

About the Smart Vector, just do the count bytecode instructions and gas meter counts, then will know then will know which way is be more gas efficient.

About AIP-9, I took a look, Sorry, I don't know what is that benefit for gas optimization.

**Comment by davidiw** [comment]
You can pack multiple resources together.
